### ISSUE TITLE
rootly_team.id returned is not valid as input into rootly_workflow_incident group_ids 

### ISSUE THREAD

**Issue by pierzapin** [rootlyhq/terraform-provider-rootly#35]
Possibly an issue of expectation, but I was hoping to see the data.rootly_teams.grp_security.id value as the guid-style id as per the API - what is returned is a (provider assigned?) integer style id that won't be accepted as valid rootly_workflow_incident group_ids content.

The https://api.rootly.com/v1/teams API call returns:
{
      "id": "**4566dd9a-e368-4288-8be7-b32eab46270f**",
      "type": "groups",
      "attributes": {
        "slug": "security",
        ....
      }
}

But the TF id is "1661805916"

### Terraform Version
Terraform v 1.2.8 on windows_amd64

### Affected Resource(s)
rootly_workflow_incident

### Terraform Configuration Files
data "rootly_teams" "grp_security" {
  slug = "security"
}

resource "rootly_workflow_incident" "tftest" {
  name        = "TF Test"
  description = "testing the tf creation of incident workflows"
  command = "create-jira-incident-workflow"
  group_ids          = [     "4566dd9a-e368-4288-8be7-b32eab46270f",
                                      "908af556-aab3-4372-94f4-91aee86c2081", 
                                      data.rootly_teams.grp_security.id    ]
  trigger_params {
    incident_condition_kind   = "ANY"
  }
}

### Debug Output
https://gist.github.com/pierzapin/d18c74158bf3ed6cebdb7eff033f7149

### Expected Behavior
The security team is added to the set of workflow team conditions

### Actual Behavior
The resource id for the team data element is rejected as invalid

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` and confirm with 'yes'

**Comment by alexmingoia** [comment]
Hello Piers. Update to v0.1.27 and change `data.teams` to `data.team` (plural to singular).

Example:

```terraform
data "rootly_team" "grp_security" {
  slug = "security"
}

resource "rootly_workflow_incident" "tftest" {
  name = "TF Test"
  description = "testing the tf creation of incident workflows"
  command = "create-jira-incident-workflow"
  group_ids = [ "4566dd9a-e368-4288-8be7-b32eab46270f", "908af556-aab3-4372-94f4-91aee86c2081", data.rootly_team.grp_security.id ]
  trigger_params {
    incident_condition_kind = "ANY"
  }
}
```

**Comment by pierzapin** [comment]
Thanks so much, @alexmingoia! That's just the help I needed.
