### ISSUE TITLE
`OpsGenie Team / External ID` not supported in the provider.

### ISSUE THREAD

**Issue by tasansga** [rootlyhq/terraform-provider-rootly#39]
# Feature request

Setting `OpsGenie Team / External ID` not supported in the provider.

In the rootly UI it is possible to set/edit a field called `OpsGenie Team / External ID`. This field currently cannot be provisioned with the rootly terraform provider and [doesn't seem to exist in the source](https://github.com/rootlyhq/terraform-provider-rootly/blob/main/provider/resource_team.go).

It is also not possible to read this field with a manual, former import through the UI, because [the data source does not expose it either](https://github.com/rootlyhq/terraform-provider-rootly/blob/main/provider/data_source_team.go).

The OpsGenie terraform provider does export the team id and we're using terraform to provision both OpsGenie and rootly so this value is available to us - would it be possible to add support for the `OpsGenie Team / External ID` field to the rootly terraform provider so we can provision the mapping?

### Terraform Version
```
Terraform v1.5.6
on linux_amd64
```

### Affected Resource(s)
- rootly_team

**Comment by kwent** [comment]
Addressed in https://github.com/rootlyhq/terraform-provider-rootly/releases/tag/v1.1.3
