### ISSUE TITLE
Missing escalation_level resource

### ISSUE THREAD

**Issue by heimweh** [rootlyhq/terraform-provider-rootly#65]
### Terraform Version
OpenTofu v1.8.2

### Affected Resource(s)
Please list the resources as a list, for example:
- `rootly_escalation_level`

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl

resource "rootly_escalation_level" "test" {}
```

### Expected Behavior
What should have happened?

I should be able to create escalation levels

### Actual Behavior
What actually happened?

Resource is there (https://github.com/rootlyhq/terraform-provider-rootly/blob/main/provider/resource_escalation_level.go) but not attached to the provider:

https://github.com/rootlyhq/terraform-provider-rootly/blob/7f060e73ec7123b389803c57748a6598f1971b45/provider/provider.go#L100

**Comment by alexmingoia** [comment]
This should be fixed in 2.7.0

**Comment by heimweh** [comment]
Awesome, thanks @alexmingoia :pray:
