### ISSUE TITLE
assign owner to schedule

### ISSUE THREAD

**Issue by schmidtjohannes** [rootlyhq/terraform-provider-rootly#70]
Hi,
is there way to assign an owner to https://registry.terraform.io/providers/rootlyhq/rootly/latest/docs/resources/schedule?

like

```
data "rootly_user" "owner" {
  email = "rootly@company.com"
}
resource "rootly_schedule" "example" {
  name           = "Test-Schedule"
  description = "a test schedule"
  owner_id.   = data.rootly_user.owner.id
}
```

Thanks in advance

**Comment by kwent** [comment]
Fixed in https://github.com/rootlyhq/terraform-provider-rootly/releases/tag/v2.14.0
